# Generated by Django 4.2.5 on 2023-10-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_rename_date_image_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=255, verbose_name='Comment'),
        ),
    ]
